### PR TITLE
A more uniform distribution

### PR DESCRIPTION
**Pull request by TotoShampoin**
Just generating 2 angles on a 3d sphere doesn't make a uniform distribution.
One of them needs to be square-rooted on its hemisphere.

That's basically what I did here.

### CODE REVIEW

**Comment by JulesFouchy** [comment]
Do you have an article proving your formula ? I couldn't find it anywhere.
Also I am pretty sure that `float r = sqrt(random.z);` should be `float r = pow(random.z, 1./3.);`  instead. See [Method 16 of this article](https://extremelearning.com.au/how-to-generate-uniformly-random-points-on-n-spheres-and-n-balls/).

**Comment by TotoShampoin** [comment]
It was trial and error on my part, so I'll just show you my experiment that led to the formula.  
I can't remember where I get that square root rule from, probably one of Sebastian Lague's videos, but it helped.

https://github.com/CoolLibs/Lab/assets/41761945/1711421d-ad14-4f35-b08d-79f456850a42

**Comment by JulesFouchy** [comment]
Yes the sampling on the surface of the sphere looks good, I'm talking about the square root on the radius, that controls how the inside of the sphere is filled in. I think this one should be a cube root.

**Comment by TotoShampoin** [comment]
As for that paper, it doesn't seem to be the same formula. Close, but not quite.  
That formula seems to be projecting a circle onto a sphere.

But maybe it is the cube root that should be used in 3d

**Comment by TotoShampoin** [comment]
> Yes the sampling on the surface of the sphere looks good, I'm talking about the square root on the radius, that controls how the inside of the sphere is filled in. I think this one should be a cube root.

In 3d, maybe. So that would be included in the if(3D)

**Comment by JulesFouchy** [comment]
One other nice thing about their formula is that is is slightly more efficient : 1 less cos and 1 less sin.
And in general, I prefer proven formulas to ones that have been found through trial-and-error (even if I'm pretty sure yours is equivalent to the one in the article). I'd prefer if you used their formula.

**Comment by JulesFouchy** [comment]
Unrelated comment: it would be nice to put these functions for random points in disks and balls inside rand.glsl, so that they can be easily reused later.

**Pull request merged**
